config/routes.rb
Rails.application.routes.draw do

  root 'pages#index'

  get 'pages/home'

  devise_scope :user do
    get "/sign_in" => "devise/sessions#new"
    get "/sign_up" => "devise/registrations#new", as: "new_user_registration"
  end

  devise_for :users, controllers: { registrations: 'registrations' }

  resources :users, :only => [:show]

  resources :organizations


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :organization
  has_many :reservations
  has_many :pairs
end

app/models/organization.rb
class Organization < ActiveRecord::Base
  belongs_to :admin, class_name: User
  has_many :events
end

app/models/pair.rb
class Pair < ApplicationRecord
  belongs_to :event
  belongs_to :driver, class_name: 'Reservation', foreign_key: 'person_1'
  belongs_to :navigator, class_name: 'Reservation', foreign_key: 'person_2'
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :event
  belongs_to :skill
  belongs_to :reservation_status
  has_many :driven_pairs, class_name: 'Pair', foreign_key: 'person_1'
  has_many :navigated_pairs, class_name: 'Pair', foreign_key: 'person_2'

  def pairs
    driven_pairs + navigated_pairs
  end
end

app/models/reservation_status.rb
class ReservationStatus < ApplicationRecord
  has_many :reservations
end

app/models/skill.rb
class Skill < ApplicationRecord
  has_many :reservations
end

app/models/user.rb
class User < ApplicationRecord
  # Virtual attribute for authenticating by either username or email
  # This is in addition to a real persisted field like 'username'
  attr_accessor :login

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :authentication_keys => [:login]

  validates :username,
    :presence => true,
    :uniqueness => {
      :case_sensitive => false
    }

  # Checks to ensure that a username cannot be set that might match an existing email.
  validate :validate_username
  
  validates_presence_of :first_name, :last_name, :username

  has_many :organizations, foreign_key: 'admin_id'
  has_many :reservations
  has_many :events, through: :reservations
  has_many :skills, through: :reservations
  has_many :driven_pairs, through: :reservations
  has_many :navigated_pairs, through: :reservations
  delegate :pairs, to: :reservation

  SKILL_LEVELS = %w(Beginner Intermediate Advanced)

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_hash).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      conditions[:email].downcase! if conditions[:email]
      where(conditions.to_hash).first
    end
  end

  private

  def validate_username
    if User.where(email: username).exists?
      errors.add(:username, :invalid)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  respond_to :html

  def index
    @organizations = Organization.all
  end

  def new
    @organization = Organization.new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end

    private

      def organization_params
        params.require(:organization).permit(:name, :description, :admin_id)
      end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    if signed_in?
      redirect_to current_user
    end
  end
end

app/controllers/pairs_controller.rb
class PairsController < ApplicationController
  def index
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :username, :email, :password, :password_confirmation, :skill_level)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :username, :email, :password, :password_confirmation, :current_password, :skill_level)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: :show

  def show
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type.to_sym]
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} fade in") do
              concat content_tag(:button, "&times".html_safe, class: "close", data: { dismiss: 'alert' })
              concat message
            end)
    end
    nil
  end

  def title(page_title)
    content_for :title, page_title.to_s
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pairs_helper.rb
module PairsHelper
end

app/views/layouts/_flash_messages.html.erb
<div class="container" id="flash_messages">
  <%= flash_messages %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <a class="navbar-brand" href="<%= root_url %>">Pairs</a>

    <ul class='nav navbar-nav navbar-right'>
      <% if signed_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dashboard <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Profile</a></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'Organizations', organizations_path %></li>
            <li><a href="#">Events</a></li>
          </ul>
        </li>
      <% end %>

      <li class='divider-vertical'></li>
      <% if signed_in? %>
        <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "Sign In", new_user_session_path %></li>
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pairs2 | <%= yield(:title) %></title>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <%= render 'layouts/flash_messages' %>

    <%= yield %>
  </body>
</html>

app/views/organizations/_form.html.erb
<%= simple_form_for(@organization) do |f| %>
  <%= f.input :name %>
  <%= f.association :admin %>
  <%= f.input :description %>
  <%= f.submit 'Create', class: 'btn btn-default' %>
<% end %>

app/views/organizations/index.html.erb
<div class="container">
  <h1 class='text-center'>Organizations</h1>
  <p class='lead text-center'>View existing organizations or <a href='#'>create</a> a new one.</p>
  <div class="row">
    <div class="col-md-3">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h4 class="panel-title">Panel title</h4>
        </div>
        <div class="panel-body">
          Panel content
        </div>
      </div>
    </div>
  </div>
</div>

app/views/organizations/new.html.erb
<% title 'Add Group' %>

<div class="container">
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <h1>Add Group</h1>

      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/pages/index.html.erb
<% title "A superior pairing app." %>

<div class="container">
  <h1 class='text-center'>Welcome to the Pairs App!</h1>

  <div class="row">
    <p class='lead text-center'>Our partner organizations use pairs for coordinating mentoring and pairing. <a href='#'>Add your group</a> today.</p>

    <div class="col-md-3">
      <div class="panel panel-default">
        <div class="panel-body">
          Panel content
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <h3 class='text-center'>Events</h3>
    <p class='lead text-center'>Check out one of these great events.</p>

    <div class="col-md-3">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h4 class="panel-title">Panel title</h4>
        </div>
        <div class="panel-body">
          Panel content
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/sign_up.html.erb
<% title "Sign Up" %>
<div class="container">
  <h1 class="text-center">Pairs Sign Up</h1>
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <%= simple_form_for @user do |f| %>
        <%= f.input :first_name %>
        <%= f.input :last_name %>
        <%= f.input :email %>
        <%= f.input :username %>
        <%= f.input :skill_level, collection: User::SKILL_LEVELS.zip((0..2).to_a) %>
        <%= f.submit "Sign Up!", class: "btn btn-default" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <h1>Profile</h1>
    </div>
  </div>
</div>